# -*- coding: utf-8 -*-
"""KNN.ipynb + SVM

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tThncP990cDUp7KO3n_BMr6E4yfNWl7S
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from scipy import stats

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/completeData.csv').astype({'valence_tags': np.float32, 'arousal_tags':np.float32, 'dominance_tags':np.float32})

from ast import literal_eval
for x in range(len(df['seeds'])):
  df['seeds'][x] = literal_eval(df['seeds'][x])

df2 = df.drop(columns=['lastfm_url', 'track', 'artist','mbid','spotify_id','genre','type','id','uri','track_href','analysis_url'])
df2 = df2.astype({'valence_tags': np.float64, 'arousal_tags':np.float64, 'dominance_tags':np.float64, 'danceability':np.float64, 'energy':np.float64, 'speechiness':np.float64, 'acousticness':np.float64, 'instrumentalness':np.float64, 'liveness':np.float64})

mood = 'calm'

"""IF THE MOOD IS PRESENT, THEN 1.
IF THE SONG DOES NOT ELICIT THE MOOD, THEN 0. 
"""

moods = []
for i in range(len(df2)):
  if(mood in df2['seeds'][i]):
    moods.append(1)
  else:
    moods.append(0)

df2['mood'] = moods
df2 = df2.drop(columns=['seeds'])

X = pd.concat([df2[df2.mood == 0].sample(921), df2[df2.mood == 1].sample(921)])
y = X['mood']
X = X.drop(columns=['mood','Unnamed: 0','number_of_emotion_tags', 'valence_tags', 'arousal_tags', 'dominance_tags'])

from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier()
classifier.fit(X_train, y_train)

"""how to know which metric to use??"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, f1_score

precisions = []

# Calculating f1 score for K values between 1 and 40
for i in range(1, 300):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train, y_train)
    pred_i = knn.predict(X_test)
    # using average='weighted' to calculate a weighted average for the 4 classes 
    precisions.append(precision_score(y_test, pred_i, average='weighted'))

plt.figure(figsize=(12, 6))
plt.plot(range(1, 300), precisions, color='red', linestyle='dashed', marker='o',
         markerfacecolor='blue', markersize=10)
plt.title('Precision Score K Value')
plt.xlabel('K Value')
plt.ylabel('Precision Score')

from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, f1_score

accuracies = []

# Calculating f1 score for K values between 1 and 40
for i in range(1, 300):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train, y_train)
    pred_i = knn.predict(X_test)
    # using average='weighted' to calculate a weighted average for the 4 classes 
    accuracies.append(accuracy_score(y_test, pred_i))

plt.figure(figsize=(12, 6))
plt.plot(range(1, 300), accuracies, color='red', linestyle='dashed', marker='o',
         markerfacecolor='blue', markersize=10)
plt.title('Accuracy Score K Value')
plt.xlabel('K Value')
plt.ylabel('Accuracy Score')

maxAccuracy = 0
maxInd2 = 0
for x in range(len(accuracies)): 
  if(accuracies[x]>maxAccuracy):
    maxAccuracy = accuracies[x]
    maxInd2 = x+1
print(maxAccuracy, maxInd2)

maxPrecision = 0
maxInd = 0
for x in range(len(precisions)): 
  if(precisions[x]>maxPrecision):
    maxPrecision = precisions[x]
    maxInd = x+1
print(maxPrecision, maxInd)

from sklearn.metrics import classification_report

classifierBest = KNeighborsClassifier(n_neighbors=maxInd)
classifierBest.fit(X_train, y_train)
y_predBest = classifierBest.predict(X_test)
print(classification_report(y_test, y_predBest))

print(confusion_matrix(y_test, y_predBest))
print(accuracy_score(y_test,y_predBest))
print(precision_score(y_test,y_predBest))
print(recall_score(y_test,y_predBest))
print(f1_score(y_test,y_predBest))

from sklearn.metrics import plot_confusion_matrix
plot_confusion_matrix(classifierBest, X_test, y_test)

from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

# Adding classes names for better interpretation
classes_names = ['class 0 (mood not present)','class 1 (mood present)']
cm = pd.DataFrame(confusion_matrix(y_test, y_predBest), 
                  columns=classes_names, index = classes_names)

# Seaborn's heatmap to better visualize the confusion matrix
sns.heatmap(cm, annot=True, fmt='d');

print(classification_report(y_test, y_predBest))

from sklearn import metrics
metrics.plot_roc_curve(classifierBest, X_test, y_test)

from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,classifierBest.predict_proba(X_test)[:, 1])

"""**BEFORE SVN: REVIEW WHY WE DID PRECISION OVER ACCURACY; THE GRAPHS LOOK THE SAME??**
precision - just true positives; accuracy - true positives and false negatives

# SVM: 
https://www.geeksforgeeks.org/support-vector-machine-algorithm/
https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/05.07-Support-Vector-Machines.ipynb#scrollTo=V0EuZlh-bVRT
"""

from sklearn.svm import SVC

X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, test_size=0.2)

svc_model = SVC(C= .1, kernel='linear', gamma= 1)
svc_model.fit(X_train2, y_train2)
 
prediction = svc_model .predict(X_test2)
# check the accuracy on the training set
print(svc_model.score(X_train2, y_train2))
print(svc_model.score(X_test2, y_test2))

svc_model = SVC(kernel='rbf')
svc_model.fit(X_train2, y_train2)
 
prediction = svc_model .predict(X_test2)
# check the accuracy on the training set
print(svc_model.score(X_train2, y_train2))
print(svc_model.score(X_test2, y_test2))

from sklearn.model_selection import GridSearchCV
param_grid = {'C': [0.001,0.01,0.1,1,5,10],
              'gamma': [0.0001, 0.0005, 0.001, 0.005]}
grid = GridSearchCV(svc_model, param_grid)

grid.fit(X_train2, y_train2)
print(grid.best_params_)

svc_model = grid.best_estimator_
svc_model.fit(X_train2, y_train2)

prediction = svc_model .predict(X_test2)
# check the accuracy on the training set
print(svc_model.score(X_train2, y_train2))
print(svc_model.score(X_test2, y_test2))

from sklearn.metrics import classification_report
print(classification_report(y_test2, prediction))

classes_names = ['class 1','class 0']
cm = pd.DataFrame(confusion_matrix(y_test2, prediction), 
                  columns=classes_names, index = classes_names)
                  
# Seaborn's heatmap to better visualize the confusion matrix
sns.heatmap(cm, annot=True, fmt='d');

print(classification_report(y_test2, prediction))

"""just for fun: Naive Bayes (https://www.geeksforgeeks.org/naive-bayes-classifiers/)"""

from sklearn.model_selection import train_test_split
X_train3, X_test3, y_train3, y_test3 = train_test_split(X, y, test_size=0.4, random_state=1)
  
# training the model on training set
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train3, y_train3)
  
# making predictions on the testing set
y_pred3 = gnb.predict(X_test3)
  
# comparing actual response values (y_test) with predicted response values (y_pred)
from sklearn import metrics
print("Gaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(y_test3, y_pred3)*100)

cm = pd.DataFrame(confusion_matrix(y_test3, y_pred3), 
                  columns=classes_names, index = classes_names)
                  
# Seaborn's heatmap to better visualize the confusion matrix
sns.heatmap(cm, annot=True, fmt='d');

from sklearn.naive_bayes import BernoulliNB
bnb = BernoulliNB()
bnb.fit(X_train3, y_train3)
  
# making predictions on the testing set
y_pred4 = bnb.predict(X_test3)
  
# comparing actual response values (y_test) with predicted response values (y_pred)
from sklearn import metrics
print("Gaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(y_test3, y_pred4)*100)


cm = pd.DataFrame(confusion_matrix(y_test3, y_pred4), 
                  columns=classes_names, index = classes_names)
                  
# Seaborn's heatmap to better visualize the confusion matrix
sns.heatmap(cm, annot=True, fmt='d');